#!/bin/bash
# This is a simple build script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

version=${PLAY_VERSION:2.1.3}

mkdir ${OPENSHIFT_PLAY2JAVA_DIR}logs
